### ISSUE TITLE
Maximum size of dictionary

### ISSUE THREAD

**Issue by richp10** [cespare/go-smaz#8]
Hi - I am trying to use a large dictionary but it breaks the decoding. 

What is the maximum size - I can't figure this out from the code!

**Comment by cespare** [comment]
Do you mean you're trying to alter the code to use a different dictionary with more than 254 strings?

That won't work because of how smaz works. When decoding a smaz string,

- Byte 0 - 253 each correspond to a dictionary string
- Byte 254 means "verbatim byte"
- Byte 255 means verbatim string (next byte is the length)

So there's no way to reference more than 254 dictionary codes. You'd have to design your own encoding if you wanted to use a larger dictionary. For example, you could say that

- 0 - 126 represent 1-byte codes
- 127 - 253 are the first byte of 2-byte codes
- 254 is verbatim byte
- 255 is verbatim string

Then you could have a dictionary of 126 + (126 * 256) = 32256 strings, at the cost of less efficient encoding of random data.

A more sophisticated solution could be to use a text corpus to build up a static Huffman tree.

**Comment by richp10** [comment]
Ah thanks - sorry for such a basic question, I see it now! I think I can cover a good set of strings within the 234 strings and still optimize of edge case where common strings repeat.  Thanks again..

**Comment by cespare** [comment]
You're welcome!
